In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df=pd.read_csv('/content/drive/MyDrive/GP ITI/GP_cleaned.csv',parse_dates=True)
df.head()

event_time event_type  product_id          category_id  \
0  2019-10-01 00:00:26       view     5875317  2029082628195353599   
1  2019-10-01 00:00:28       view     5692917  1487580004857414477   
2  2019-10-01 00:00:48       view     5819638  1487580008162526182   
3  2019-10-01 00:00:53       view     5856191  1487580006350586771   
4  2019-10-01 00:01:11       view     5733176  1487580009362096156   

                   category_code    brand  price    user_id  \
0                            NaN      NaN   1.59  474232307   
1                            NaN  lianail   5.54  555446068   
2                            NaN      NaN  21.75  546705258   
3  appliances.environment.vacuum   runail  24.44  507355498   
4                            NaN      NaN   0.60  543446752   

                           user_session  
0  445f2b74-5e4c-427e-b7fa-6e0a28b156fe  
1  4257671a-efc8-4e58-96c2-3ab457916d78  
2  3b5c65c0-bb1c-453b-b340-4ebf973a3136  
3  944c7e9b-40bd-4112-a05b-81e73f37e0c0  
4  4a01cad9-7368-fd9e-d907-d4d85de0b55c

In [4]:
df['event_time'] = pd.to_datetime(df['event_time'])

Our recommendation system for this period is based on the previous analysis which indicated that the number of purchases rose from approximately 15 to 24 in November.





In [5]:
start_date = dt.datetime(2019, 11, 15)
end_date = dt.datetime(2019, 11, 24)
purchase = df[(df['event_type'] == 'purchase') & (df['event_time'].between(start_date, end_date))][['user_session', 'product_id']]
purchase = purchase.drop_duplicates()

# group purchases by user_session and create a list of unique product_ids in each session
sessions = purchase.groupby('user_session')['product_id'].apply(list)

# create a new DataFrame with user_session as index and columns for each unique product_id
session_products = pd.DataFrame(sessions.tolist(), index=sessions.index)

# view the resulting DataFrame
session_products

0          1          2    \
user_session                                                          
0005adfb-7989-8f89-e867-09aa92883a50  5866057  5839238.0  5839239.0   
000737df-40bd-46dc-9ab7-96bc4df35719  5767806  5747360.0  5550700.0   
001b689e-b936-4cf4-9f3d-b9be62309e85  5815570  5815568.0  5815567.0   
00245c8f-6203-4997-a89a-9e7ee844c613  5705002  5691555.0    89350.0   
00307b7c-0e71-4e75-a78f-32b8ff4aba1b  5629984  5700487.0  5751422.0   
...                                       ...        ...        ...   
ffe5a588-7aa4-4db3-b24e-81aaaeaf65c0  5878148  5877767.0  5869153.0   
ffe78b41-81c5-4cb2-a8cd-285d8c2aa752  5561576  5694639.0  5763238.0   
ffe87539-5b94-2909-e4e0-c6aadc94630a  5759492  5799407.0  5825941.0   
fff5d350-b897-4d87-8792-f9c7ef49907f  5649255  5635098.0  5897370.0   
fff8439d-1348-4070-944d-66598fccb7c6  5769921  5808333.0        NaN   

                                            3          4          5    \
user_session                                                            
0005adfb-7989-8f89-e867-09aa92883a50        NaN        NaN        NaN   
000737df-40bd-46dc-9ab7-96bc4df35719        NaN        NaN        NaN   
001b689e-b936-4cf4-9f3d-b9be62309e85  5773611.0  5754991.0  5587762.0   
00245c8f-6203-4997-a89a-9e7ee844c613        NaN        NaN        NaN   
00307b7c-0e71-4e75-a78f-32b8ff4aba1b  5809910.0  5813414.0  5826419.0   
...                                         ...        ...        ...   
ffe5a588-7aa4-4db3-b24e-81aaaeaf65c0  5869133.0  5869135.0        NaN   
ffe78b41-81c5-4cb2-a8cd-285d8c2aa752        NaN        NaN        NaN   
ffe87539-5b94-2909-e4e0-c6aadc94630a  5878958.0  5879015.0  5887964.0   
fff5d350-b897-4d87-8792-f9c7ef49907f  5549838.0        NaN        NaN   
fff8439d-1348-4070-944d-66598fccb7c6        NaN        NaN        NaN   

                                            6          7          8    \
user_session                                                            
0005adfb-7989-8f89-e867-09aa92883a50        NaN        NaN        NaN   
000737df-40bd-46dc-9ab7-96bc4df35719        NaN        NaN        NaN   
001b689e-b936-4cf4-9f3d-b9be62309e85  5899144.0     8706.0  5815571.0   
00245c8f-6203-4997-a89a-9e7ee844c613        NaN        NaN        NaN   
00307b7c-0e71-4e75-a78f-32b8ff4aba1b  5837928.0  5858898.0  5893674.0   
...                                         ...        ...        ...   
ffe5a588-7aa4-4db3-b24e-81aaaeaf65c0        NaN        NaN        NaN   
ffe78b41-81c5-4cb2-a8cd-285d8c2aa752        NaN        NaN        NaN   
ffe87539-5b94-2909-e4e0-c6aadc94630a        NaN        NaN        NaN   
fff5d350-b897-4d87-8792-f9c7ef49907f        NaN        NaN        NaN   
fff8439d-1348-4070-944d-66598fccb7c6        NaN        NaN        NaN   

                                            9    ...  269  270  271  272  273  \
user_session                                     ...                            
0005adfb-7989-8f89-e867-09aa92883a50        NaN  ...  NaN  NaN  NaN  NaN  NaN   
000737df-40bd-46dc-9ab7-96bc4df35719        NaN  ...  NaN  NaN  NaN  NaN  NaN   
001b689e-b936-4cf4-9f3d-b9be62309e85        NaN  ...  NaN  NaN  NaN  NaN  NaN   
00245c8f-6203-4997-a89a-9e7ee844c613        NaN  ...  NaN  NaN  NaN  NaN  NaN   
00307b7c-0e71-4e75-a78f-32b8ff4aba1b  5899851.0  ...  NaN  NaN  NaN  NaN  NaN   
...                                         ...  ...  ...  ...  ...  ...  ...   
ffe5a588-7aa4-4db3-b24e-81aaaeaf65c0        NaN  ...  NaN  NaN  NaN  NaN  NaN   
ffe78b41-81c5-4cb2-a8cd-285d8c2aa752        NaN  ...  NaN  NaN  NaN  NaN  NaN   
ffe87539-5b94-2909-e4e0-c6aadc94630a        NaN  ...  NaN  NaN  NaN  NaN  NaN   
fff5d350-b897-4d87-8792-f9c7ef49907f        NaN  ...  NaN  NaN  NaN  NaN  NaN   
fff8439d-1348-4070-944d-66598fccb7c6        NaN  ...  NaN  NaN  NaN  NaN  NaN   

                                      274  275  276  277  278  
user_session                                                   
0005adfb-7989-8f89-e867-09aa92883a50

We create 279 columns as the maximum number of products purchased during a single session in this period was 279.

###prepare data for model
this is list of all purchased product in a single session 

In [6]:
# Create a list of lists from a dataframe
transactions=session_products.stack().groupby(level=0).apply(list).tolist()
# Show what it looks like
transactions

[[5866057.0, 5839238.0, 5839239.0],
 [5767806.0, 5747360.0, 5550700.0],
 [5815570.0,
  5815568.0,
  5815567.0,
  5773611.0,
  5754991.0,
  5587762.0,
  5899144.0,
  8706.0,
  5815571.0],
 [5705002.0, 5691555.0, 89350.0],
 [5629984.0,
  5700487.0,
  5751422.0,
  5809910.0,
  5813414.0,
  5826419.0,
  5837928.0,
  5858898.0,
  5893674.0,
  5899851.0,
  5899852.0,
  59893.0,
  59896.0],
 [5833173.0, 5831981.0],
 [6819.0, 5528034.0],
 [5786944.0, 5810480.0, 5826419.0, 5842141.0],
 [5754161.0,
  5729011.0,
  5757291.0,
  5700046.0,
  5902148.0,
  5864626.0,
  5826185.0,
  5833319.0,
  5659751.0,
  5692527.0,
  5697542.0],
 [5815662.0,
  5767806.0,
  5839182.0,
  5820722.0,
  5834737.0,
  5820744.0,
  5700037.0,
  5587648.0,
  5834649.0],
 [5883099.0],
 [5861279.0],
 [5888554.0, 5867612.0, 5823646.0, 5823444.0],
 [5649305.0, 5786397.0, 5861591.0],
 [5688690.0, 5774072.0, 5812138.0, 5857924.0, 5886558.0],
 [5886769.0,
  5855118.0,
  5840350.0,
  5820785.0,
  5820781.0,
  5820779.0,
  5751383.

In [7]:
# Put all transactions into a single list
txns=session_products.values.reshape(-1).tolist()

# Create a dataframe using this single list and add a column for count
df_list=pd.DataFrame(txns)
df_list['Count']=1

# Group by items and rename columns
df_list=df_list.groupby(by=[0], as_index=False).count().sort_values(by=['Count'], ascending=True) # count
df_list['Percentage'] = (df_list['Count'] / df_list['Count'].sum()) # percentage
df_list=df_list.rename(columns={0 : 'Item'})

# Show dataframe
df_list

Item  Count  Percentage
19917  5907072.0      1    0.000010
5999   5766594.0      1    0.000010
12577  5843369.0      1    0.000010
5997   5766589.0      1    0.000010
5995   5766585.0      1    0.000010
...          ...    ...         ...
8725   5809912.0    308    0.002980
5342   5751422.0    317    0.003067
11312  5833330.0    338    0.003270
14141  5854897.0    412    0.003986
8723   5809910.0    700    0.006773

[19918 rows x 3 columns]

We can see that 5809910 is by far the most popular item bought, followed by 5854897.0. Meanwhile, poor old 5907072.0 has only been bought once.

Also, it is important to note that even the most frequently bought item only appears in just over 0.6% of transactions. We can use this information as a guide when setting the minimum support threshold.



In [8]:
from mlxtend.preprocessing import TransactionEncoder

# instantiate a transaction encoder
my_transactionencoder = TransactionEncoder()

# fit the transaction encoder using the list of transaction tuples
my_transactionencoder.fit(transactions)

# transform the list of transaction tuples into an array of encoded transactions
encoded_transactions = my_transactionencoder.transform(transactions)

# convert the array of encoded transactions into a dataframe
encoded_transactions_df = pd.DataFrame(encoded_transactions, columns=my_transactionencoder.columns_)
encoded_transactions_df

3762.0     3763.0     3774.0     3776.0     3806.0     3928.0     \
0          False      False      False      False      False      False   
1          False      False      False      False      False      False   
2          False      False      False      False      False      False   
3          False      False      False      False      False      False   
4          False      False      False      False      False      False   
...          ...        ...        ...        ...        ...        ...   
11567      False      False      False      False      False      False   
11568      False      False      False      False      False      False   
11569      False      False      False      False      False      False   
11570      False      False      False      False      False      False   
11571      False      False      False      False      False      False   

       3936.0     3945.0     3959.0     3978.0     ...  5906205.0  5906206.0  \
0          False      False      False      False  ...      False      False   
1          False      False      False      False  ...      False      False   
2          False      False      False      False  ...      False      False   
3          False      False      False      False  ...      False      False   
4          False      False      False      False  ...      False      False   
...          ...        ...        ...        ...  ...        ...        ...   
11567      False      False      False      False  ...      False      False   
11568      False      False      False      False  ...      False      False   
11569      False      False      False      False  ...      False      False   
11570      False      False      False      False  ...      False      False   
11571      False      False      False      False  ...      False      False   

       5906207.0  5906217.0  5906537.0  5906538.0  5907060.0  5907066.0  \
0          False      False      False      False      False      False   
1          False      False      False      False      False      False   
2          False      False      False      False      False      False   
3          False      False      False      False      False      False   
4          False      False      False      False      False      False   
...          ...        ...        ...        ...        ...        ...   
11567      False      False      False      False      False      False   
11568      False      False      False      False      False      False   
11569      False      False      False      False      False      False   
11570      False      False      False      False      False      False   
11571      False      False      False      False      False      False   

       5907067.0  5907072.0  
0          False      False  
1          False      False  
2          False      False  
3          False      False  
4          False      False  
...          ...        ...  
11567      False      False  
11568      False      False  
11569      False      False  
11570      False      False  
11571      False      False  

[11572 rows x 19918 columns]

In this binary dataset, every row represents a transaction. Columns are possible products that might appear in every transaction. Every cell contains one of two possible values:

- False – the product was not included in the transaction
- True – the transaction contains the product

In [9]:
# count items in each column
items_total = encoded_transactions_df.astype(int).sum(axis=0)
items_total.sort_values()

5907072.0      1
5766594.0      1
5843369.0      1
5766589.0      1
5766585.0      1
            ... 
5809912.0    308
5751422.0    317
5833330.0    338
5854897.0    412
5809910.0    700
Length: 19918, dtype: int64

In [10]:
# count items in each row
items_per_transaction = encoded_transactions_df.astype(int).sum(axis=1)
items_per_transaction.sort_values()

7332       1
4934       1
1265       1
730        1
4956       1
        ... 
3233     129
7734     145
10429    149
472      172
3820     279
Length: 11572, dtype: int64

Now, we can use these Series to visualize items distribution

In [11]:
#Frequent item list

# Loading items per column stats to the DataFrame
df_ = pd.DataFrame({'items': items_total.index, 'transactions': items_total.values}) 
# cloning pandas DataFrame for visualization purpose  
df_table = df_.sort_values("transactions", ascending=False)

#  Top 5 most popular products/items

df_table.head(5).style.background_gradient(cmap='viridis')

We can also visualize the frequently occurring items using TreeMap

In [12]:
# importing required module
import plotly.express as px
# to have a same origin
df_table["all"] = "Tree Map" 
# creating tree map using plotly
fig = px.treemap(df_table.head(50), path=['all', "items"], values='transactions',
                  color=df_table["transactions"].head(50), hover_data=['items'],
                  color_continuous_scale='viridis',
                )
# ploting the treemap
fig.show()

##Generating Association Rules


###FP-Growth

In [19]:
!pip install mlxtend
!pip install --upgrade mlxtend

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


frequent itemset 

In [20]:
# our min support is 7, but it has to be expressed as a percentage for mlxtend
#min_support = 4/len(txns2) 
min_support = 0.005
# compute the frequent itemsets using fpgriowth from mlxtend
from mlxtend.frequent_patterns.fpgrowth import fpgrowth
frequent_itemsets = fpgrowth(encoded_transactions_df, min_support=min_support, use_colnames = True)

# print the frequent itemsets
frequent_itemsets

support                itemsets
0    0.060491             (5809910.0)
1    0.027394             (5751422.0)
2    0.005358             (5528034.0)
3    0.007864             (5842141.0)
4    0.005790             (5810480.0)
..        ...                     ...
151  0.012357  (5809912.0, 5809910.0)
152  0.006481  (5833330.0, 5833325.0)
153  0.007000  (5816170.0, 5809910.0)
154  0.005271  (5809912.0, 5816170.0)
155  0.005876  (5833330.0, 5833323.0)

[156 rows x 2 columns]

In [21]:
# Compute the association rules based on the frequent itemsets
from mlxtend.frequent_patterns import association_rules

# compute and print the association rules
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)


antecedents  consequents  antecedent support  consequent support  \
0   (5751422.0)  (5751383.0)            0.027394            0.024542   
1   (5751383.0)  (5751422.0)            0.024542            0.027394   
2   (5849033.0)  (5751422.0)            0.021517            0.027394   
3   (5833330.0)  (5833335.0)            0.029208            0.016160   
4   (5833335.0)  (5833330.0)            0.016160            0.029208   
5   (5809912.0)  (5809910.0)            0.026616            0.060491   
6   (5809910.0)  (5809912.0)            0.060491            0.026616   
7   (5833330.0)  (5833325.0)            0.029208            0.019184   
8   (5833325.0)  (5833330.0)            0.019184            0.029208   
9   (5816170.0)  (5809910.0)            0.016592            0.060491   
10  (5816170.0)  (5809912.0)            0.016592            0.026616   
11  (5833330.0)  (5833323.0)            0.029208            0.016246   
12  (5833323.0)  (5833330.0)            0.016246            0.029208   

     support  confidence       lift  leverage  conviction  
0   0.008555    0.312303  12.725241  0.007883    1.418441  
1   0.008555    0.348592  12.725241  0.007883    1.493082  
2   0.005358    0.248996   9.089532  0.004768    1.295075  
3   0.005876    0.201183  12.449704  0.005404    1.231622  
4   0.005876    0.363636  12.449704  0.005404    1.525530  
5   0.012357    0.464286   7.675306  0.010747    1.753750  
6   0.012357    0.204286   7.675306  0.010747    1.223283  
7   0.006481    0.221893  11.566448  0.005921    1.260516  
8   0.006481    0.337838  11.566448  0.005921    1.466093  
9   0.007000    0.421875   6.974196  0.005996    1.625097  
10  0.005271    0.317708  11.936756  0.004830    1.426639  
11  0.005876    0.201183  12.383482  0.005402    1.231514  
12  0.005876    0.361702  12.383482  0.005402    1.520907

###Apriori

In [13]:
!pip install apyori

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [14]:
from apyori import apriori
rule = apriori(transactions = transactions, min_support = 0.005, min_confidence = 0.2, min_lift = 3, min_length = 2)

In [15]:

output = list(rule) # returns a non-tabular output
# putting output into a pandas dataframe
def inspect(output):
    lhs         = [tuple(result[2][0][0])[0] for result in output]
    rhs         = [tuple(result[2][0][1])[0] for result in output]
    support    = [result[1] for result in output]
    confidence = [result[2][0][2] for result in output]
    lift       = [result[2][0][3] for result in output]
    return list(zip(lhs, rhs, support, confidence, lift))
output_DataFrame = pd.DataFrame(inspect(output), columns = ['antecedents', 'consequents', 'Support', 'Confidence', 'Lift'])


In [16]:
output_DataFrame.sort_values(by='Lift',ascending=False)

antecedents  consequents   Support  Confidence       Lift
0    5751383.0    5751422.0  0.008555    0.348592  12.725241
7    5833330.0    5833335.0  0.005876    0.201183  12.449704
5    5833323.0    5833330.0  0.005876    0.361702  12.383482
4    5816170.0    5809912.0  0.005271    0.317708  11.936756
6    5833325.0    5833330.0  0.006481    0.337838  11.566448
1    5849033.0    5751422.0  0.005358    0.248996   9.089532
2    5809910.0    5809912.0  0.012357    0.204286   7.675306
3    5816170.0    5809910.0  0.007000    0.421875   6.974196

In [17]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [18]:
antecedents_list = [5751383,5833330 ,5833323 ,5816170 ,	5833325 ,	5849033 ,5809910 ,	5816170 ]
consequents_list = [5751422	,5833335,5833330	,5809912,5833330	,5751422 ,5809912 ,5809910	]
antecedents_brand_list = [df.loc[df['product_id'] == i]['brand'].values[0] for i in antecedents_list]
consequents_brand_list = [df.loc[df['product_id'] == i]['brand'].values[0] for i in consequents_list]

new_df = pd.DataFrame({'antecedents': antecedents_list, 
                       'consequents': consequents_list, 
                       'antecedents_brand': antecedents_brand_list, 
                       'consequents_brand': consequents_brand_list})

In [22]:
new_df

antecedents  consequents antecedents_brand consequents_brand
0      5751383      5751422               uno               uno
1      5833330      5833335         bpw.style         bpw.style
2      5833323      5833330         bpw.style         bpw.style
3      5816170      5809912           grattol           grattol
4      5833325      5833330         bpw.style         bpw.style
5      5849033      5751422               uno               uno
6      5809910      5809912           grattol           grattol
7      5816170      5809910           grattol           grattol